In [8]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('AfterLasso_Clinical1.csv')

In [10]:
df.head()

,Age_cat,BMI_cat,LUNG,Fever_Sympt,GI_Symp,Acuity_0,Acuity_7,Acuity_max,creat_0_cat,ddimer_0_cat,ldh_0_cat,abs_neut_3_cat,creat_3_cat,crp_3_cat,abs_neut_7_cat,abs_lymph_7_cat,creat_7_cat,crp_7_cat,Class Label
0,1,4,0,1,1,3,5,3,2,1,2,2,1,1,-1,-1,-1,-1,0
1,2,2,0,1,1,3,5,3,2,2,2,2,1,2,-1,-1,-1,-1,0
2,3,4,1,0,1,3,5,3,2,3,4,3,2,3,-1,-1,-1,-1,0
3,1,2,0,1,0,3,5,3,2,2,2,3,1,2,-1,-1,-1,-1,0
4,3,3,0,1,1,3,3,3,2,3,3,3,1,5,3,5,1,4,0

In [11]:
df

,Age_cat,BMI_cat,LUNG,Fever_Sympt,GI_Symp,Acuity_0,Acuity_7,Acuity_max,creat_0_cat,ddimer_0_cat,ldh_0_cat,abs_neut_3_cat,creat_3_cat,crp_3_cat,abs_neut_7_cat,abs_lymph_7_cat,creat_7_cat,crp_7_cat,Class Label
0,1,4,0,1,1,3,5,3,2,1,2,2,1,1,-1,-1,-1,-1,0
1,2,2,0,1,1,3,5,3,2,2,2,2,1,2,-1,-1,-1,-1,0
2,3,4,1,0,1,3,5,3,2,3,4,3,2,3,-1,-1,-1,-1,0
3,1,2,0,1,0,3,5,3,2,2,2,3,1,2,-1,-1,-1,-1,0
4,3,3,0,1,1,3,3,3,2,3,3,3,1,5,3,5,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,3,2,0,1,0,2,2,1,3,4,5,4,3,5,3,3,3,5,1
380,4,2,0,1,0,3,2,1,3,3,3,4,2,5,3,2,3,4,1
381,4,3,1,0,0,2,2,1,3,4,4,2,3,4,3,3,1,4,1
382,5,2,1,0,0,3,1,1,5,5,2,-1,-1,-1,-1,-1,-1,-1,1
383,5,2,0,1,0,2,1,1,1,3,5,3,1,4,-1,-1,-1,-1,1

In [12]:
print(df.shape)
print(df.isnull().sum())

(384, 19)
Age_cat            0
BMI_cat            0
LUNG               0
Fever_Sympt        0
GI_Symp            0
Acuity_0           0
Acuity_7           0
Acuity_max         0
creat_0_cat        0
ddimer_0_cat       0
ldh_0_cat          0
abs_neut_3_cat     0
creat_3_cat        0
crp_3_cat          0
abs_neut_7_cat     0
abs_lymph_7_cat    0
creat_7_cat        0
crp_7_cat          0
Class Label        0
dtype: int64

In [13]:
X = df.drop('Class Label', axis=1)
y = df['Class Label']

In [14]:
X = preprocessing.scale(X)
y = preprocessing.scale(y)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [16]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(268, 18)
(268,)
(116, 18)
(116,)

In [17]:
regression_model = LinearRegression()

regression_model.fit(X_train, y_train)

LinearRegression()

In [18]:
ridge = Ridge(alpha=0.25, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=1000000, solver='auto', random_state=None)
ridge.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(

Ridge(alpha=0.25, normalize=False, tol=1000000)

In [19]:
print ("Ridge model:", (ridge.coef_))

Ridge model: [ 0.09765453  0.03659195 -0.06758517  0.07296277 -0.07111201  0.66848957
 -0.18250017 -1.19854661  0.06361624 -0.03793081  0.00952051 -0.04638159
 -0.07485624 -0.07725286 -0.13328284 -0.04701012  0.01023508 -0.10457818]

In [20]:
lasso = Lasso(alpha=0.001)
lasso.fit(X_train,y_train)
print ("Lasso model:", (lasso.coef_))

Lasso model: [ 0.09499755  0.03463812 -0.06661774  0.0712446  -0.07031538  0.66786486
 -0.18124714 -1.19948774  0.06210842 -0.03609518  0.00667206 -0.04934458
 -0.06933721 -0.0759498  -0.12808357 -0.04621468  0.0014377  -0.10250405]

In [21]:
print("Linear Regression Model Training Score: ", regression_model.score(X_train, y_train))
print("Linear Regression Model Testing Score: ",regression_model.score(X_test, y_test))
print("Ridge Regression Model Training Score: ",ridge.score(X_train, y_train))
print("Ridge Regression Model Testing Score: ",ridge.score(X_test, y_test))
print("Lasso Regression Model Training Score: ",lasso.score(X_train, y_train))
print("Lasso Regression Model Testing Score: ",lasso.score(X_test, y_test))

Linear Regression Model Training Score:  0.7429039439869456
Linear Regression Model Testing Score:  0.7529197846871518
Ridge Regression Model Training Score:  0.7428917365631147
Ridge Regression Model Testing Score:  0.7528991300621569
Lasso Regression Model Training Score:  0.7428532314993491
Lasso Regression Model Testing Score:  0.7536019410150178