In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.datasets import load_diabetes

In [2]:
df = pd.read_csv('Protein_final_ut2.csv',
                 lineterminator='\n')

In [3]:
df.isnull().values.any()

False

In [4]:
df.head()

,Patients ID,A1E959,A1L4H1,A4D1B5,A6NI73,B1AKI9,NTproBNP,O00161,O00175,O00182,...,Q9Y662,Q9Y680,Q9Y6A5,Q9Y6D9,Q9Y6E0,Q9Y6K9,Q9Y6N7,Q9Y6Q6,Q9Y6Y9,Class Label\r
0,1_D0,-0.4919,-2.0764,-4.1174,-1.6798,-1.6368,-2.9075,3.2226,-4.9658,-0.5558,...,-1.7002,0.1028,1.4372,-1.2237,0.0942,3.1638,-2.5676,-2.5675,-1.0704,0
1,10_D0,-0.4128,-2.5055,-4.2090,-2.1186,-2.1341,-2.1834,2.3743,-3.5027,-0.9061,...,-1.4034,0.0871,1.5215,-0.7514,0.3801,2.7710,-2.0708,-3.3429,-1.5707,0
2,100_D0,-0.1184,-2.1845,-4.7553,-1.0313,-2.4404,-2.3786,2.8104,-5.8802,0.0117,...,0.0634,0.6548,1.3863,0.6855,0.7598,3.3714,-2.0427,-1.8044,-1.5958,0
3,101_D0,2.3431,-1.9234,-4.1818,-1.0012,-3.0546,-1.6429,1.4504,-4.5658,-0.1437,...,-0.7388,1.7710,0.5739,0.5000,3.9538,1.6872,-2.5787,-2.6166,-1.1554,0
4,103_D0,-0.4058,-1.8440,-4.1875,-1.9196,-2.4053,-2.1893,1.5982,-1.2853,-1.9186,...,-1.6360,1.0028,0.1051,-1.8314,0.5992,1.6747,-2.2349,-2.6691,-1.5367,0

In [5]:
df.shape

(344, 1465)

In [6]:
df.describe()

,A1E959,A1L4H1,A4D1B5,A6NI73,B1AKI9,NTproBNP,O00161,O00175,O00182,O00186,...,Q9Y662,Q9Y680,Q9Y6A5,Q9Y6D9,Q9Y6E0,Q9Y6K9,Q9Y6N7,Q9Y6Q6,Q9Y6Y9,Class Label\r
count,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,...,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000
mean,-0.470059,-1.813984,-4.477865,-1.044711,-2.082938,0.060057,1.713144,-3.391276,0.099004,0.473133,...,-1.149020,0.212039,1.038295,0.689311,0.364303,1.986945,-2.224542,-1.478763,-0.971954,0.127907
std,0.538593,0.540712,0.473263,0.596265,0.746470,2.319700,1.742279,1.449535,0.823210,0.542354,...,0.583525,0.461374,0.898655,1.147414,0.423182,1.493663,0.460204,1.246090,0.572666,0.334473
min,-1.635500,-3.676900,-5.401600,-2.609700,-3.629900,-3.201900,-1.628300,-6.630300,-2.551400,-0.628700,...,-2.512600,-0.843300,-0.552100,-2.096600,-1.527800,-0.671600,-3.854400,-3.572400,-2.253800,0.000000
25%,-0.767250,-2.164625,-4.723800,-1.406675,-2.582150,-1.598475,0.216350,-4.442250,-0.391900,0.081125,...,-1.535800,-0.062175,0.314275,-0.062800,0.130850,0.638450,-2.554350,-2.350950,-1.346500,0.000000
50%,-0.535650,-1.807250,-4.525300,-1.059100,-2.141750,-0.701850,1.619550,-3.478900,0.061400,0.382650,...,-1.184100,0.150800,0.875750,0.641600,0.360550,1.910600,-2.253500,-1.778450,-1.020950,0.000000
75%,-0.267550,-1.484450,-4.358050,-0.688600,-1.658950,1.333775,3.090575,-2.506450,0.687850,0.735475,...,-0.847550,0.388450,1.607025,1.431300,0.597250,3.196625,-2.012475,-0.950400,-0.677925,0.000000
max,4.745300,0.122400,-0.061900,1.134400,0.775500,8.916200,6.125500,1.452500,2.647600,3.075700,...,1.407900,3.185600,5.159300,4.976200,3.953800,6.256200,0.029200,3.446100,1.425500,1.000000

In [7]:
X=df.drop(['Class Label\r','Patients ID'],axis=1)
y=df['Class Label\r']

In [8]:
print(X)

     A1E959  A1L4H1  A4D1B5  A6NI73  B1AKI9  NTproBNP  O00161  O00175  O00182  \
0   -0.4919 -2.0764 -4.1174 -1.6798 -1.6368   -2.9075  3.2226 -4.9658 -0.5558
1   -0.4128 -2.5055 -4.2090 -2.1186 -2.1341   -2.1834  2.3743 -3.5027 -0.9061
2   -0.1184 -2.1845 -4.7553 -1.0313 -2.4404   -2.3786  2.8104 -5.8802  0.0117
3    2.3431 -1.9234 -4.1818 -1.0012 -3.0546   -1.6429  1.4504 -4.5658 -0.1437
4   -0.4058 -1.8440 -4.1875 -1.9196 -2.4053   -2.1893  1.5982 -1.2853 -1.9186
..      ...     ...     ...     ...     ...       ...     ...     ...     ...
339 -0.2350 -1.1699 -4.8938 -0.3536 -1.5352    0.7698  2.8747 -2.7360  1.7449
340 -0.6947 -2.7393 -4.5285 -1.9382 -3.3073    3.6338  0.9896 -2.8089 -0.9757
341 -0.5367 -1.9027 -4.1107 -0.7150 -2.2652   -0.6560  3.0865 -2.5204  0.8739
342  0.2077 -2.4165 -4.6623 -0.1746 -2.3921    2.9758  0.2672 -3.9186 -0.1152
343 -0.0601 -1.3297 -4.6848 -0.0891 -0.9847    5.0848  2.8900 -5.0421  2.2074

     O00186  ...  Q9Y653  Q9Y662  Q9Y680  Q9Y6A5  Q9Y6D9  Q9Y6E0  Q9Y6K9  \
0    0.7527  ... -2.6860 -1.7002  0.1028  1.4372 -1.2237  0.0942  3.1638
1    0.8234  ... -2.9263 -1.4034  0.0871  1.5215 -0.7514  0.3801  2.7710
2    0.4151  ... -2.2744  0.0634  0.6548  1.3863  0.6855  0.7598  3.3714
3    0.5307  ... -1.5901 -0.7388  1.7710  0.5739  0.5000  3.9538  1.6872
4    0.0727  ... -2.0379 -1.6360  1.0028  0.1051 -1.8314  0.5992  1.6747
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
339  0.4183  ...  1.8874 -0.5587  0.7055  1.1355  2.9278  0.3610  3.0448
340  0.3767  ... -2.4301 -2.2458  0.0149  0.4818  0.0778  0.3326  1.6640
341  0.7147  ...  1.2652 -1.7044 -0.0113  1.7115  2.1189  0.5588  2.9604
342 -0.3202  ... -0.6997 -1.7821  0.0849 -0.1629  0.3361  0.2940 -0.2996
343  0.6525  ... -0.7984 -0.2616  1.0928  1.8185  3.0001  1.0360  2.9919

     Q9Y6N7  Q9Y6Q6  Q9Y6Y9
0   -2.5676 -2.5675 -1.0704
1   -2.0708 -3.3429 -1.5707
2   -2.0427 -1.8044 -1.5958
3   -2.5787 -2.6166 -1.1554
4   -2.2349 -2.6691 -1.5367
..      ...     ...     ...
339 -2.3253 -0.3235 -0.5668
340 -2.7799  0.4357 -1.0733
341 -2.2659 -1.4649 -0.9493
342 -2.8025  0.3821 -0.3629
343 -2.0279  0.5061 -0.3701

[344 rows x 1463 columns]

In [9]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
339    1
340    1
341    1
342    1
343    1
Name: Class Label\r, Length: 344, dtype: int64

In [10]:
#column_names = list(df.columns.values)
#print(column_names)

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
print(X_train.shape[1])

1463

In [13]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [14]:
lasso = Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=100000, tol=0.0001)

In [15]:
lasso.fit(X, y)

Lasso(alpha=0.01, max_iter=100000)

In [16]:
selected_features = np.arange(1463)[lasso.coef_ !=0]
print("Selected Features: ", selected_features)

Selected Features:  [   0   25   47   75   95   96  104  109  111  126  143  153  154  157
  159  174  175  182  183  185  207  211  212  216  221  225  226  241
  263  265  273  297  314  340  354  362  363  373  375  378  401  418
  427  444  448  450  465  471  482  491  494  516  522  534  556  558
  588  595  601  607  613  619  625  628  665  668  676  699  702  703
  717  718  723  725  742  761  764  765  770  771  774  782  807  841
  849  851  866  874  884  887  893  897  910  914  919  969  971  976
  980  984  999 1029 1040 1048 1050 1063 1070 1082 1087 1093 1095 1097
 1108 1109 1112 1116 1117 1118 1141 1142 1143 1154 1170 1177 1179 1187
 1191 1205 1215 1239 1290 1293 1337 1338 1342 1352 1356 1369 1375 1382
 1385 1390 1421 1427 1439 1449 1452 1453]

In [17]:
list=[]
for i in selected_features:
    #print(df.columns[i+1])
    list.append(df.columns[i+1])

In [18]:
list

['A1E959',
 'O00533',
 'O14793',
 'O43240',
 'O43854',
 'O43895',
 'O60462',
 'O60635',
 'O60760',
 'O75340',
 'O76038',
 'O94907',
 'O94985',
 'O95256',
 'O95379',
 'O95750',
 'O95760',
 'O95988',
 'O95994',
 'O96013',
 'P01138',
 'P01229',
 'P01236',
 'P01275',
 'P01579',
 'P01589',
 'P01591',
 'P03950',
 'P05113',
 'P05164',
 'P05783',
 'P07711',
 'P08571',
 'P09525',
 'P10145',
 'P10721',
 'P10747',
 'P12318',
 'P12532',
 'P12724',
 'P14136',
 'P15090',
 'P15336',
 'P16860',
 'P17516',
 'P17676',
 'P19256',
 'P19801',
 'P20273',
 'P20827',
 'P20936',
 'P22676',
 'P23229',
 'P24387',
 'P28325',
 'P28827',
 'P30838',
 'P31994',
 'P32970',
 'P34947',
 'P35225',
 'P35475',
 'P35813',
 'P36222',
 'P42701',
 'P42785',
 'P43629',
 'P49747',
 'P49771',
 'P49788',
 'P51452',
 'P51531',
 'P51693',
 'P51888',
 'P55082',
 'P58499',
 'P60484',
 'P60568',
 'P62736',
 'P63098',
 'P68106',
 'P78423',
 'Q02643',
 'Q07960',
 'Q0Z7S8',
 'Q10588',
 'Q12968',
 'Q13231',
 'Q13426',
 'Q13459',
 'Q13574',
 'Q13822',
 'Q14242',
 'Q14512',
 'Q14773',
 'Q16864',
 'Q29980_Q29983',
 'Q3KPI0',
 'Q4LE39',
 'Q5JZY3',
 'Q6ISS4',
 'Q6YHK3',
 'Q7L8A9',
 'Q7Z6M3',
 'Q7Z7D3',
 'Q8IU54',
 'Q8IWL2',
 'Q8N474',
 'Q8N8S7',
 'Q8NBZ7',
 'Q8NCC3',
 'Q8NEZ2',
 'Q8TD06',
 'Q8TD46',
 'Q8TDQ1',
 'Q8WTT0',
 'Q8WTU2',
 'Q8WTV0',
 'Q92820',
 'Q92823',
 'Q92832',
 'Q969V3',
 'Q96GW7',
 'Q96JP9',
 'Q96KN2',
 'Q96NZ8',
 'Q96PL1',
 'Q99538',
 'Q99748',
 'Q9BXJ7',
 'Q9HAW4',
 'Q9HBG7',
 'Q9NX58',
 'Q9NXA8',
 'Q9NZC2',
 'Q9P0M4',
 'Q9P232',
 'Q9UGM5',
 'Q9UHF4',
 'Q9UJ71',
 'Q9UJM8',
 'Q9UK85',
 'Q9Y243',
 'Q9Y286',
 'Q9Y4X3',
 'Q9Y5W5',
 'Q9Y639',
 'Q9Y653']

In [19]:
new_df = df[list].copy()

In [20]:
new_df.head()

,A1E959,O00533,O14793,O43240,O43854,O43895,O60462,O60635,O60760,O75340,...,Q9UHF4,Q9UJ71,Q9UJM8,Q9UK85,Q9Y243,Q9Y286,Q9Y4X3,Q9Y5W5,Q9Y639,Q9Y653
0,-0.4919,0.0983,-2.5061,-0.8852,-0.4555,-1.5365,-1.8878,-0.5249,-1.5093,-1.6057,...,-0.4619,-1.6595,-0.3062,-1.5383,0.1785,-2.3708,-1.6989,-2.5205,-0.9395,-2.6860
1,-0.4128,-2.1145,-2.1944,-1.2593,0.0862,-2.5725,-2.5367,-0.4660,-1.7140,-2.0919,...,-0.8532,-1.9887,-3.7973,-2.0863,0.5192,-2.1511,-1.3429,-2.0744,-0.9847,-2.9263
2,-0.1184,-2.8544,-1.5425,-0.7903,0.0563,-1.2906,-1.4967,-0.6516,-1.1682,-1.3145,...,-0.1494,-2.0962,-0.9036,-1.6766,-0.0389,-1.7278,-1.3336,-1.0752,-1.4976,-2.2744
3,2.3431,-1.6653,-1.1607,-1.1215,-0.6337,-1.9994,-1.9916,-0.5478,-1.3573,-2.4856,...,-1.0347,-2.2349,-3.2673,-2.1599,0.2928,-1.6677,-3.0117,-1.5189,-1.2781,-1.5901
4,-0.4058,-1.9007,-2.1913,-1.0143,0.1754,-4.1595,-1.9541,-0.3659,-0.9669,-1.5082,...,-1.0991,-1.8062,-4.0754,-2.4352,0.2169,-2.5172,-0.8271,-1.8143,-0.5371,-2.0379

In [21]:
new_df.to_csv('chosen_columns.csv')