In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.datasets import load_diabetes

In [2]:
df = pd.read_csv('Protein_final_ut2.csv',
                 lineterminator='\n')

In [3]:
df.isnull().values.any()

False

In [4]:
df.head()

,Patients ID,A1E959,A1L4H1,A4D1B5,A6NI73,B1AKI9,NTproBNP,O00161,O00175,O00182,...,Q9Y662,Q9Y680,Q9Y6A5,Q9Y6D9,Q9Y6E0,Q9Y6K9,Q9Y6N7,Q9Y6Q6,Q9Y6Y9,Class Label\r
0,1_D0,-0.4919,-2.0764,-4.1174,-1.6798,-1.6368,-2.9075,3.2226,-4.9658,-0.5558,...,-1.7002,0.1028,1.4372,-1.2237,0.0942,3.1638,-2.5676,-2.5675,-1.0704,0
1,10_D0,-0.4128,-2.5055,-4.2090,-2.1186,-2.1341,-2.1834,2.3743,-3.5027,-0.9061,...,-1.4034,0.0871,1.5215,-0.7514,0.3801,2.7710,-2.0708,-3.3429,-1.5707,0
2,100_D0,-0.1184,-2.1845,-4.7553,-1.0313,-2.4404,-2.3786,2.8104,-5.8802,0.0117,...,0.0634,0.6548,1.3863,0.6855,0.7598,3.3714,-2.0427,-1.8044,-1.5958,0
3,101_D0,2.3431,-1.9234,-4.1818,-1.0012,-3.0546,-1.6429,1.4504,-4.5658,-0.1437,...,-0.7388,1.7710,0.5739,0.5000,3.9538,1.6872,-2.5787,-2.6166,-1.1554,0
4,103_D0,-0.4058,-1.8440,-4.1875,-1.9196,-2.4053,-2.1893,1.5982,-1.2853,-1.9186,...,-1.6360,1.0028,0.1051,-1.8314,0.5992,1.6747,-2.2349,-2.6691,-1.5367,0

In [5]:
df.shape

(344, 1465)

In [6]:
df.describe()

,A1E959,A1L4H1,A4D1B5,A6NI73,B1AKI9,NTproBNP,O00161,O00175,O00182,O00186,...,Q9Y662,Q9Y680,Q9Y6A5,Q9Y6D9,Q9Y6E0,Q9Y6K9,Q9Y6N7,Q9Y6Q6,Q9Y6Y9,Class Label\r
count,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,...,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000
mean,-0.470059,-1.813984,-4.477865,-1.044711,-2.082938,0.060057,1.713144,-3.391276,0.099004,0.473133,...,-1.149020,0.212039,1.038295,0.689311,0.364303,1.986945,-2.224542,-1.478763,-0.971954,0.127907
std,0.538593,0.540712,0.473263,0.596265,0.746470,2.319700,1.742279,1.449535,0.823210,0.542354,...,0.583525,0.461374,0.898655,1.147414,0.423182,1.493663,0.460204,1.246090,0.572666,0.334473
min,-1.635500,-3.676900,-5.401600,-2.609700,-3.629900,-3.201900,-1.628300,-6.630300,-2.551400,-0.628700,...,-2.512600,-0.843300,-0.552100,-2.096600,-1.527800,-0.671600,-3.854400,-3.572400,-2.253800,0.000000
25%,-0.767250,-2.164625,-4.723800,-1.406675,-2.582150,-1.598475,0.216350,-4.442250,-0.391900,0.081125,...,-1.535800,-0.062175,0.314275,-0.062800,0.130850,0.638450,-2.554350,-2.350950,-1.346500,0.000000
50%,-0.535650,-1.807250,-4.525300,-1.059100,-2.141750,-0.701850,1.619550,-3.478900,0.061400,0.382650,...,-1.184100,0.150800,0.875750,0.641600,0.360550,1.910600,-2.253500,-1.778450,-1.020950,0.000000
75%,-0.267550,-1.484450,-4.358050,-0.688600,-1.658950,1.333775,3.090575,-2.506450,0.687850,0.735475,...,-0.847550,0.388450,1.607025,1.431300,0.597250,3.196625,-2.012475,-0.950400,-0.677925,0.000000
max,4.745300,0.122400,-0.061900,1.134400,0.775500,8.916200,6.125500,1.452500,2.647600,3.075700,...,1.407900,3.185600,5.159300,4.976200,3.953800,6.256200,0.029200,3.446100,1.425500,1.000000

In [7]:
X=df.drop(['Class Label\r','Patients ID'],axis=1)
y=df['Class Label\r']

In [8]:
print(X)

     A1E959  A1L4H1  A4D1B5  A6NI73  B1AKI9  NTproBNP  O00161  O00175  O00182  \
0   -0.4919 -2.0764 -4.1174 -1.6798 -1.6368   -2.9075  3.2226 -4.9658 -0.5558
1   -0.4128 -2.5055 -4.2090 -2.1186 -2.1341   -2.1834  2.3743 -3.5027 -0.9061
2   -0.1184 -2.1845 -4.7553 -1.0313 -2.4404   -2.3786  2.8104 -5.8802  0.0117
3    2.3431 -1.9234 -4.1818 -1.0012 -3.0546   -1.6429  1.4504 -4.5658 -0.1437
4   -0.4058 -1.8440 -4.1875 -1.9196 -2.4053   -2.1893  1.5982 -1.2853 -1.9186
..      ...     ...     ...     ...     ...       ...     ...     ...     ...
339 -0.2350 -1.1699 -4.8938 -0.3536 -1.5352    0.7698  2.8747 -2.7360  1.7449
340 -0.6947 -2.7393 -4.5285 -1.9382 -3.3073    3.6338  0.9896 -2.8089 -0.9757
341 -0.5367 -1.9027 -4.1107 -0.7150 -2.2652   -0.6560  3.0865 -2.5204  0.8739
342  0.2077 -2.4165 -4.6623 -0.1746 -2.3921    2.9758  0.2672 -3.9186 -0.1152
343 -0.0601 -1.3297 -4.6848 -0.0891 -0.9847    5.0848  2.8900 -5.0421  2.2074

     O00186  ...  Q9Y653  Q9Y662  Q9Y680  Q9Y6A5  Q9Y6D9  Q9Y6E0  Q9Y6K9  \
0    0.7527  ... -2.6860 -1.7002  0.1028  1.4372 -1.2237  0.0942  3.1638
1    0.8234  ... -2.9263 -1.4034  0.0871  1.5215 -0.7514  0.3801  2.7710
2    0.4151  ... -2.2744  0.0634  0.6548  1.3863  0.6855  0.7598  3.3714
3    0.5307  ... -1.5901 -0.7388  1.7710  0.5739  0.5000  3.9538  1.6872
4    0.0727  ... -2.0379 -1.6360  1.0028  0.1051 -1.8314  0.5992  1.6747
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
339  0.4183  ...  1.8874 -0.5587  0.7055  1.1355  2.9278  0.3610  3.0448
340  0.3767  ... -2.4301 -2.2458  0.0149  0.4818  0.0778  0.3326  1.6640
341  0.7147  ...  1.2652 -1.7044 -0.0113  1.7115  2.1189  0.5588  2.9604
342 -0.3202  ... -0.6997 -1.7821  0.0849 -0.1629  0.3361  0.2940 -0.2996
343  0.6525  ... -0.7984 -0.2616  1.0928  1.8185  3.0001  1.0360  2.9919

     Q9Y6N7  Q9Y6Q6  Q9Y6Y9
0   -2.5676 -2.5675 -1.0704
1   -2.0708 -3.3429 -1.5707
2   -2.0427 -1.8044 -1.5958
3   -2.5787 -2.6166 -1.1554
4   -2.2349 -2.6691 -1.5367
..      ...     ...     ...
339 -2.3253 -0.3235 -0.5668
340 -2.7799  0.4357 -1.0733
341 -2.2659 -1.4649 -0.9493
342 -2.8025  0.3821 -0.3629
343 -2.0279  0.5061 -0.3701

[344 rows x 1463 columns]

In [9]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
339    1
340    1
341    1
342    1
343    1
Name: Class Label\r, Length: 344, dtype: int64

In [10]:
#column_names = list(df.columns.values)
#print(column_names)

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
print(X_train.shape[1])

1463

In [13]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [14]:
lasso = Lasso(alpha=0.0008, copy_X=True, fit_intercept=True,random_state=3, max_iter=10000, tol=0.0001,
              precompute=False, warm_start=1, positive=False, selection='random')

In [15]:
lasso.fit(X, y)

C:\Users\baibh\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py:541: FutureWarning: Passing an int for a boolean parameter is deprecated in version 1.2 and won't be supported anymore in version 1.4.
  warnings.warn(

Lasso(alpha=0.0008, max_iter=10000, random_state=3, selection='random',
      warm_start=1)

In [16]:
selected_features = np.arange(1463)[lasso.coef_ !=0]
print("Selected Features: ", selected_features)

Selected Features:  [   0    1    2    7   22   25   33   36   37   41   46   47   53   64
   67   68   75   82   83   85   89   90   99  104  106  109  111  126
  128  132  143  149  153  154  156  157  159  161  165  174  175  182
  192  196  207  209  210  211  212  216  217  222  226  232  233  241
  242  243  261  262  263  265  273  274  275  297  314  320  323  330
  336  340  343  354  355  362  363  373  375  378  379  380  386  390
  397  401  403  409  410  413  415  419  421  423  426  427  429  441
  442  444  448  450  453  458  460  461  471  479  482  492  494  495
  504  506  510  514  516  524  534  542  556  558  571  573  585  588
  589  590  595  601  602  606  607  609  612  613  617  619  625  630
  638  641  648  653  654  660  664  676  677  685  702  708  711  713
  717  718  723  725  727  732  733  739  740  743  745  748  751  753
  756  758  761  762  764  765  774  776  778  782  791  793  794  801
  804  806  807  818  820  822  825  840  841  848  849  851  852  860
  861  869  874  875  876  879  884  887  893  895  897  908  912  914
  919  925  931  936  949  957  978  988  998  999 1006 1011 1013 1020
 1027 1029 1030 1031 1048 1056 1061 1063 1070 1074 1077 1079 1082 1085
 1087 1090 1095 1097 1098 1104 1108 1109 1110 1112 1116 1117 1118 1120
 1122 1124 1125 1126 1129 1136 1139 1141 1142 1143 1145 1154 1156 1162
 1166 1168 1177 1179 1187 1192 1205 1214 1215 1216 1221 1224 1238 1239
 1241 1243 1255 1263 1266 1274 1285 1293 1305 1313 1314 1323 1325 1327
 1330 1333 1335 1337 1338 1342 1352 1353 1356 1359 1364 1369 1371 1374
 1375 1376 1384 1385 1407 1416 1421 1422 1427 1428 1439 1441 1446 1447
 1452 1453 1454 1455 1458]

In [17]:
list=[]
count=0
for i in selected_features:
    #print(df.columns[i+1])
    list.append(df.columns[i+1])
    count+=1

In [18]:
print(count)
list

327

['A1E959',
 'A1L4H1',
 'A4D1B5',
 'O00175',
 'O00399',
 'O00533',
 'O00748',
 'O14579',
 'O14594',
 'O14713',
 'O14788',
 'O14793',
 'O14917',
 'O15263',
 'O15389',
 'O15394',
 'O43240',
 'O43524',
 'O43557',
 'O43570',
 'O43699',
 'O43707',
 'O60240',
 'O60462',
 'O60542',
 'O60635',
 'O60760',
 'O75340',
 'O75356',
 'O75493',
 'O76038',
 'O94779',
 'O94907',
 'O94985',
 'O95183',
 'O95256',
 'O95379',
 'O95407',
 'O95502',
 'O95750',
 'O95760',
 'O95988',
 'P00740',
 'P00813',
 'P01138',
 'P01215',
 'P01222',
 'P01229',
 'P01236',
 'P01275',
 'P01298',
 'P01583',
 'P01591',
 'P02452',
 'P02462',
 'P03950',
 'P03956',
 'P04054',
 'P05107',
 'P05112',
 'P05113',
 'P05164',
 'P05783',
 'P05937',
 'P06127',
 'P07711',
 'P08571',
 'P08758',
 'P08962',
 'P09237',
 'P09466',
 'P09525',
 'P09619',
 'P10145',
 'P10147',
 'P10721',
 'P10747',
 'P12318',
 'P12532',
 'P12724',
 'P12830',
 'P12872',
 'P13500',
 'P13598',
 'P13726',
 'P14136',
 'P14207',
 'P14555',
 'P14625',
 'P14784',
 'P15018',
 'P15121',
 'P15151',
 'P15289',
 'P15328',
 'P15336',
 'P15514',
 'P16455',
 'P16562',
 'P16860',
 'P17516',
 'P17676',
 'P17936',
 'P18428',
 'P18564',
 'P18627',
 'P19801',
 'P20062',
 'P20273',
 'P20849',
 'P20936',
 'P21217_Q11128',
 'P21810',
 'P21964',
 'P22105',
 'P22307',
 'P22676',
 'P23280',
 'P24387',
 'P25786',
 'P28325',
 'P28827',
 'P29466',
 'P29475',
 'P30533',
 'P30838',
 'P31146',
 'P31350',
 'P31994',
 'P32970',
 'P33151',
 'P34913',
 'P34947',
 'P34998',
 'P35218',
 'P35225',
 'P35442',
 'P35475',
 'P35813',
 'P36888',
 'P38484',
 'P39748',
 'P40225',
 'P41208',
 'P41217',
 'P41586',
 'P42658',
 'P43629',
 'P45452',
 'P47992',
 'P49771',
 'P50452',
 'P50583',
 'P50749',
 'P51452',
 'P51531',
 'P51693',
 'P51888',
 'P52789',
 'P53539',
 'P53582',
 'P55008',
 'P55039',
 'P55103',
 'P55259',
 'P55291',
 'P55789',
 'P55957',
 'P56470',
 'P57771',
 'P58499',
 'P58546',
 'P60484',
 'P60568',
 'P68106',
 'P78324',
 'P78333',
 'P78423',
 'P80370',
 'P82980',
 'P98073',
 'Q01543',
 'Q02083',
 'Q02487',
 'Q02643',
 'Q03431',
 'Q04759',
 'Q04900',
 'Q05516',
 'Q07954',
 'Q07960',
 'Q08AG7',
 'Q0Z7S8',
 'Q10588',
 'Q10589',
 'Q12864',
 'Q12866',
 'Q13093',
 'Q13231',
 'Q13232',
 'Q13241',
 'Q13291',
 'Q13426',
 'Q13459',
 'Q13574',
 'Q13651',
 'Q13822',
 'Q14213_Q8NEV9',
 'Q14435',
 'Q14512',
 'Q14773',
 'Q15113',
 'Q15303',
 'Q15582',
 'Q16552',
 'Q16674',
 'Q49AH0',
 'Q5T4W7',
 'Q6GTX8',
 'Q6ISS4',
 'Q6PCB0',
 'Q6UWL2',
 'Q6UWN8',
 'Q6UXB4',
 'Q6WN34',
 'Q6YHK3',
 'Q6ZMC9',
 'Q6ZMH5',
 'Q7Z6M3',
 'Q86U17',
 'Q86WV1',
 'Q8IU54',
 'Q8IWL2',
 'Q8IYS5',
 'Q8N149',
 'Q8N2G4',
 'Q8N474',
 'Q8N6P7',
 'Q8N8S7',
 'Q8NBJ7',
 'Q8NCC3',
 'Q8NEZ2',
 'Q8NFP4',
 'Q8TAD2',
 'Q8TD06',
 'Q8TD46',
 'Q8TDL5',
 'Q8TDQ1',
 'Q8WTT0',
 'Q8WTU2',
 'Q8WTV0',
 'Q8WUW1',
 'Q8WV07',
 'Q8WVQ1',
 'Q8WWN9',
 'Q8WWY7',
 'Q8WXI7',
 'Q92597',
 'Q92752',
 'Q92820',
 'Q92823',
 'Q92832',
 'Q92851',
 'Q969V3',
 'Q96A56',
 'Q96D42',
 'Q96F46',
 'Q96FQ6',
 'Q96JP9',
 'Q96KN2',
 'Q96NZ8',
 'Q96PP9',
 'Q99538',
 'Q99731',
 'Q99748',
 'Q99795',
 'Q99988',
 'Q9BQR3',
 'Q9BXJ1',
 'Q9BXJ7',
 'Q9BXS1',
 'Q9BY76',
 'Q9C0C4',
 'Q9H156',
 'Q9H2A7',
 'Q9H4A9',
 'Q9HA65',
 'Q9HBG7',
 'Q9NP79',
 'Q9NQ38',
 'Q9NQ76',
 'Q9NRG1',
 'Q9NRM6',
 'Q9NRW1',
 'Q9NS71',
 'Q9NTU7',
 'Q9NWQ8',
 'Q9NX58',
 'Q9NXA8',
 'Q9NZC2',
 'Q9P0M4',
 'Q9P0V8',
 'Q9P232',
 'Q9UBM4',
 'Q9UBW5',
 'Q9UGM5',
 'Q9UHC6',
 'Q9UHF1',
 'Q9UHF4',
 'Q9UHL4',
 'Q9UJA9',
 'Q9UJM8',
 'Q9UMF0',
 'Q9UQB8',
 'Q9Y243',
 'Q9Y258',
 'Q9Y286',
 'Q9Y2B0',
 'Q9Y4X3',
 'Q9Y5A7',
 'Q9Y5L3',
 'Q9Y5P4',
 'Q9Y639',
 'Q9Y653',
 'Q9Y662',
 'Q9Y680',
 'Q9Y6E0']

In [19]:
new_df = df[list].copy()

In [20]:
new_df.head()

,A1E959,A1L4H1,A4D1B5,O00175,O00399,O00533,O00748,O14579,O14594,O14713,...,Q9Y2B0,Q9Y4X3,Q9Y5A7,Q9Y5L3,Q9Y5P4,Q9Y639,Q9Y653,Q9Y662,Q9Y680,Q9Y6E0
0,-0.4919,-2.0764,-4.1174,-4.9658,-1.5078,0.0983,-1.6269,-0.6419,-2.4856,0.6629,...,-0.3123,-1.6989,1.5245,-0.7825,-0.2378,-0.9395,-2.6860,-1.7002,0.1028,0.0942
1,-0.4128,-2.5055,-4.2090,-3.5027,-0.4386,-2.1145,-2.4055,-0.0242,-1.4080,0.6427,...,-0.0746,-1.3429,1.7145,-0.3893,0.2223,-0.9847,-2.9263,-1.4034,0.0871,0.3801
2,-0.1184,-2.1845,-4.7553,-5.8802,-1.2304,-2.8544,-1.8016,0.2606,-1.6189,0.1459,...,-0.4919,-1.3336,1.8759,-0.5889,0.7959,-1.4976,-2.2744,0.0634,0.6548,0.7598
3,2.3431,-1.9234,-4.1818,-4.5658,0.1475,-1.6653,-2.2297,0.8708,-1.5441,0.0437,...,-0.0619,-3.0117,0.6757,-0.7900,1.3011,-1.2781,-1.5901,-0.7388,1.7710,3.9538
4,-0.4058,-1.8440,-4.1875,-1.2853,-0.7245,-1.9007,-1.8618,0.1797,-1.5928,0.2228,...,-0.2828,-0.8271,0.2489,-0.4025,-0.2951,-0.5371,-2.0379,-1.6360,1.0028,0.5992

In [21]:
new_df.to_csv('Run22.csv')